version: '2.4'

services:

  rabbitmq:
    image: 'cytomine/rabbitmq:v1.1.2'
    restart: always
    networks:
      network_3:
        aliases:
            - rabbitmq
      software_router:
        aliases:
            - rabbitmq
    expose:
      - '5672'
      - '15672'


  postgresql:
    image: 'cytomine/postgis:v2.0.0'
    restart: always
    mem_limit: 8g
    networks:
      network_3:
        aliases:
            - postgresql
    volumes:
      - "postgis_data:/var/lib/postgresql"


  mongodb:
    image: 'cytomine/mongodb:v1.1.2'
    restart: always
    networks:
      network_3:
        aliases:
            - mongodb
    volumes:
      - mongodb_data:/data/db
    expose:
      - '27017'


  bioformat:
    image: 'cytomine/bioformat:v1.1.2'
    restart: always
    networks:
      network_2:
        aliases:
            - bioformat
    environment:
      - "BIOFORMAT_PORT=${BIOFORMAT_PORT}"
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"


  memcached:
    build:
      context: "./memcached"
    restart: always
    networks:
      network_1:
        aliases:
            - memcached


  iipoff:
    build:
      context: "./iipOff"
    depends_on:
      - memcached
    restart: always
    privileged: true
    networks:
      network_1:
        aliases:
            - iipoff
      nginx:
        aliases:
            - iipoff
    environment:
      - NB_IIP_PROCESS=$NB_IIP_PROCESS
    volumes:
      - "${IMS_STORAGE_PATH}:$IMS_STORAGE_PATH"


  iipcyto:
    build:
      context: "./iipCyto"
    restart: always
    networks:
      network_1:
        aliases:
            - iipcyto
      nginx:
        aliases:
            - iipcyto
    privileged: true
    environment:
      - NB_IIP_PROCESS=$NB_IIP_PROCESS
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"


  ims:
    build:
      context: "./ims"
    restart: always
    networks:
      network_1:
        aliases:
          - ims
      network_2:
        aliases:
            - ims
      nginx:
        aliases:
            - ims
    environment:
      - "NB_IIP_PROCESS=${NB_IIP_PROCESS}"
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"

  core:
    restart: always
    depends_on:
      - mongodb
      - postgresql
      - rabbitmq
    build:
      context: "./core"
    networks:
      network_3:
        aliases:
            - core
      nginx:
        aliases:
            - core
    volumes:
    - "/etc/localtime:/etc/localtime"


  digipat-frontend:
    restart: always
    build:
      context: "./digipat-frontend"
    networks:
      nginx:
        aliases:
          - digipat-frontend
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    expose:
      - '80'
    ports:
      - '8001:80'


  nginx:
    restart: always
    depends_on:
      - core
      - ims
      - iipoff
      - iipcyto
      - digipat-frontend
    build:
      context: "./nginx"
    networks:
      nginx:
        aliases:
            - nginx
    volumes:
    - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    ports:
    - 80:80

  software_router:
    build:
      context: ./software_router
    privileged: true
    depends_on:
      - core
    networks:
      software_router:
        aliases:
            - software_router
    environment:
      - "CORE_URL=http://${CORE_URL}"
      - "RABBITMQ_PUB_KEY=${RABBITMQ_PUB_KEY}"
      - "RABBITMQ_PRIV_KEY=${RABBITMQ_PRIV_KEY}"
    volumes:
    - "${ALGO_PATH}:/software_router/algo/"




volumes:
  postgis_data:
  mongodb_data:

networks:
  # TODO: lag bedre navn på nettverkene
  network_1:
  network_2:
  network_3:
  nginx:
  software_router:


