version: '3.1'

services:
  wizard_mongo:
    env_file:
      - .env
    container_name: ${WIZARD_MONGO_CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.init_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${WIZARD_MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${WIZARD_MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${WIZARD_MONGODB_DATABASE}
    volumes:
      - mongodevdata:/data/db
    networks:
        mongo:
          aliases:
            - mongodb
  
  wizard_backend:
    env_file:
      - .env
    container_name: ${WIZARD_BACKEND_CONTAINER_NAME}
    image: docker.pkg.github.com/histographer/wizard-backend/wizard-backend:prod
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wizard-backend.rule=Host(`${WIZARD_BACKEND_URL}`)'
      - 'traefik.http.routers.wizard-backend.entrypoints=web'
      - 'traefik.http.routers.wizard-backend.middlewares=cors'
      - "traefik.http.routers.wizard-backend.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.wizard-backend-secured.rule=Host(`${WIZARD_BACKEND_URL}`)" # <== Your Domain Name for the https rule 
      - "traefik.http.routers.wizard-backend-secured.entrypoints=web-secured" # <== Defining entrypoint for https 
      - "traefik.http.routers.wizard-backend-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      - 'traefik.http.routers.wizard-backend-secured.middlewares=cors'
    restart: always
    environment:
      WIZARD_MONGODB_HOST: ${WIZARD_MONGO_CONTAINER_NAME}
    networks:
        mongo:
          aliases:
            - wizard-backend 
        traefik:

        
  digipat-frontend:
    env_file:
      - '.env'
    restart: always
    image: 'docker.pkg.github.com/histographer/wizard-frontend/wizard-frontend:prod'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.digipat-frontend.rule=Host(`${CORE_URL}`)'
      - 'traefik.http.routers.digipat-frontend.entrypoints=web'
      - 'traefik.http.routers.digipat-frontend.middlewares=cors'
      - "traefik.http.routers.digipat-frontend.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - 'traefik.http.routers.digipat-frontend-secured.middlewares=cors'
      - 'traefik.http.routers.digipat-frontend-secured.rule=Host(`${CORE_URL}`)'
      - "traefik.http.routers.digipat-frontend-secured.entrypoints=web-secured" # <== Defining entrypoint for https
      - "traefik.http.routers.digipat-frontend-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
    networks:
      traefik:
        aliases:
          - digipat-frontend
    volumes:
      - '${IMS_BUFFER_PATH_HOST}:/tmp/uploaded'
    expose:
      - '80'

networks:
    traefik:
        external: true
    mongo:

volumes:
  mongodevdata:



