version: '3'

services:
  mongo_compare:
    image: mongo:latest
    container_name: compare_mongo
    restart: always
    env_file:
      - '.env'
    networks:
      - traefik
    volumes:
      - mongodata:/data/db
      - ./database/db-init/:/docker-entrypoint-initdb.d

  compare_frontend:
    image: docker.pkg.github.com/histographer/compare-frontend/compare-frontend:prod
    container_name: compare_frontend
    networks:
      - traefik
    labels:
      - 'traefik.enable=true' # <== Enable traefik to proxy this container
      - 'traefik.http.routers.compare-frontend.rule=Host(`${COMPARE_FRONTEND_URL}`)' # <== Your Domain Name goes here for the http rule
      - 'traefik.http.routers.compare-frontend.entrypoints=web' # <== Defining the entrypoint for http, 
      - "traefik.http.routers.compare-frontend.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.compare-frontend-secured.rule=Host(`${COMPARE_FRONTEND_URL}`)" # <== Your Domain Name for the https rule 
      - "traefik.http.routers.compare-frontend-secured.entrypoints=web-secured" # <== Defining entrypoint for https 
      - "traefik.http.routers.compare-frontend-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

  compare_backend:
    image: docker.pkg.github.com/histographer/compare-backend/compare-backend:prod
    container_name: compare_backend
    env_file:
      - '.env'
    networks:
      - traefik
    labels:
      - 'traefik.enable=true' # <== Enable traefik to proxy this container
      - 'traefik.http.routers.compare-backend.rule=Host(`${COMPARE_BACKEND_URL}`)' # <== Your Domain Name goes here for the http rule
      - 'traefik.http.routers.compare-backend.entrypoints=web' # <== Defining the entrypoint for http
      - "traefik.http.routers.compare-backend.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.compare-backend-secured.rule=Host(`${COMPARE_BACKEND_URL}`)" # <== Your Domain Name for the https rule 
      - "traefik.http.routers.compare-backend-secured.entrypoints=web-secured" # <== Defining entrypoint for https
      - "traefik.http.routers.compare-backend-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      - "traefik.http.routers.compare-backend-secured.middlewares=cors"
    ports:
      - 9292:8080
volumes:
  mongodata:

networks:
  traefik:
    external: true
