version: '3.7'


volumes:
  postgis_data:
  mongodb_data:
  pat-or-nat-data:

networks:
  network_1:
  network_2:
  network_3:
  nginx:
  software_router:
  pat-or-nat:

secrets:
  ADMIN_PWD:
    external: true
  ADMIN_PUB_KEY:
    external: true
  ADMIN_PRIV_KEY:
    external: true
  SUPERADMIN_PUB_KEY:
    external: true
  SUPERADMIN_PRIV_KEY:
    external: true
  RABBITMQ_PUB_KEY:
    external: true
  RABBITMQ_PRIV_KEY:
    external: true
  IMS_PUB_KEY:
    external: true
  IMS_PRIV_KEY:
    external: true
  SERVER_ID:
    external: true
  PATORNAT_MONGODB_PASSWORD:
    external: true
  PATORNAT_MONGODB_ROOT_PASSWORD:
    external: true
  PATORNAT_INITDB_MONGODB_ROOT_PASSWORD:
    external: true


services:

  rabbitmq:
    env_file:
      - ".env"
    image: 'cytomine/rabbitmq:v1.1.2'
    restart: always
    networks:
      network_3:
        aliases:
          - rabbitmq
      software_router:
        aliases:
          - rabbitmq
    expose:
      - '5672'
      - '15672'


  postgresql:
    env_file:
      - ".env"
    image: 'cytomine/postgis:v2.0.0'
    restart: always
    networks:
      network_3:
        aliases:
          - postgresql
    volumes:
      - "postgis_data:/var/lib/postgresql"


  mongodb:
    env_file:
      - ".env"
    image: 'cytomine/mongodb:v1.1.2'
    restart: always
    networks:
      network_3:
        aliases:
          - mongodb
    volumes:
      - mongodb_data:/data/db
    expose:
      - '27017'


  bioformat:
    env_file:
      - ".env"
    image: 'cytomine/bioformat:v1.1.2'
    restart: always
    networks:
      network_2:
        aliases:
          - bioformat
    environment:
      - "BIOFORMAT_PORT=${BIOFORMAT_PORT}"
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"

  memcached:
    env_file:
      - ".env"
    build:
      context: "./memcached"
    image: "docker.pkg.github.com/histographer/infrastructure/memcached"
    restart: always
    networks:
      network_1:
        aliases:
          - memcached


  iipoff:
    env_file:
      - ".env"
    build:
      context: "./iipOff"
    image: "docker.pkg.github.com/histographer/infrastructure/iipoff"
    depends_on:
      - memcached
    restart: always
    privileged: true
    networks:
      network_1:
        aliases:
          - iipoff
      nginx:
        aliases:
          - iipoff
    volumes:
      - "${IMS_STORAGE_PATH}:$IMS_STORAGE_PATH"


  iipcyto:
    env_file:
      - ".env"
    build:
      context: "./iipCyto"
    image: "docker.pkg.github.com/histographer/infrastructure/iipcyto"
    restart: always
    networks:
      network_1:
        aliases:
          - iipcyto
      nginx:
        aliases:
          - iipcyto
    privileged: true
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"


  ims:
    env_file:
      - ".env"
    secrets:
      - IMS_PUB_KEY
      - IMS_PRIV_KEY
    build:
      context: "./ims"
    image: "docker.pkg.github.com/histographer/infrastructure/ims"
    restart: always
    depends_on:
      - core
    networks:
      network_1:
        aliases:
          - ims
      network_2:
        aliases:
          - ims
      nginx:
        aliases:
          - ims
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"

  core:
    env_file:
      - ".env"
    secrets:
      - ADMIN_PWD
      - ADMIN_PUB_KEY
      - ADMIN_PRIV_KEY
      - SUPERADMIN_PUB_KEY
      - SUPERADMIN_PRIV_KEY
      - IMS_PUB_KEY
      - IMS_PRIV_KEY
      - RABBITMQ_PRIV_KEY
      - RABBITMQ_PUB_KEY
      - SERVER_ID
    restart: always
    depends_on:
      - mongodb
      - postgresql
      - rabbitmq
    build:
      context: "./core"
    image: "docker.pkg.github.com/histographer/infrastructure/core"
    networks:
      network_3:
        aliases:
          - core
      nginx:
        aliases:
          - core


  digipat-frontend:
    env_file:
      - ".env"
    restart: always
    image: "docker.pkg.github.com/histographer/digipat-frontend/digipat-frontend"
    networks:
      nginx:
        aliases:
          - digipat-frontend
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    expose:
      - '80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s



  pat-or-nat-frontend:
    env_file:
      - ".env"
    restart: always
    image: "docker.pkg.github.com/histographer/pat-or-nat-frontend/pat-or-nat-frontend"
    networks:
      nginx:
        aliases:
          - pat-or-nat-frontend
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    expose:
      - '80'

  # TODO: Should use the existing mongodb service later
  pat-or-nat-db:
    env_file:
      - ".env"
    image: mongo:latest
    restart: always
    networks:
      pat-or-nat:
        aliases:
          - pat-or-nat-db
    secrets:
      - PATORNAT_INITDB_MONGODB_ROOT_PASSWORD
      - PATORNAT_MONGODB_PASSWORD
    volumes:
      - pat-or-nat-data:/data/db
      - ./database/db-init/:/docker-entrypoint-initdb.d

  pat-or-nat-backend:
    restart: always
    env_file:
      - ".env"
    secrets:
      - PATORNAT_MONGODB_PASSWORD
    image: "docker.pkg.github.com/histographer/pat-or-nat-backend/pat-or-nat-backend"
    depends_on:
      - pat-or-nat-db
    networks:
      nginx:
        aliases:
          - pat-or-nat-backend
      pat-or-nat:
        aliases:
          - pat-or-nat-backend


  analysis-rest-api:
    image: "docker.pkg.github.com/histographer/analysis-rest-api/analysis-rest-api"
    env_file:
      - ".env"
    networks:
      nginx:
        aliases:
          - analysis-rest-api
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 120s



  nginx:
    restart: always
    env_file:
      - ".env"
    depends_on:
      - digipat-frontend
      - core
      - ims
      - iipoff
      - iipcyto
      - pat-or-nat-frontend
      - pat-or-nat-backend
      - analysis-rest-api
    image: "docker.pkg.github.com/histographer/infrastructure/nginx-prod"
    build:
      context: "./nginx"
    networks:
      nginx:
        aliases:
          - nginx
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://digipat-frontend:80"]
      interval: 10s
      timeout: 5s
      retries: 10

  software_router:
    env_file:
      - ".env"
    secrets:
      - RABBITMQ_PUB_KEY
      - RABBITMQ_PRIV_KEY
    build:
      context: "./software_router"
    image: "docker.pkg.github.com/histographer/infrastructure/software_router"
    privileged: true
    depends_on:
      - core
      - nginx
    networks:
      software_router:
        aliases:
          - software_router
    volumes:
      - "${ALGO_PATH}:/software_router/algo/"





