version: '3.7'


volumes:
  postgis_data:
  mongodb_data:
  compare-data:

networks:
  network_1:
  network_2:
  network_3:
  nginx:
  software_router:
  compare:

secrets:
  ADMIN_PWD:
    external: true
  ADMIN_PUB_KEY:
    external: true
  ADMIN_PRIV_KEY:
    external: true
  SUPERADMIN_PUB_KEY:
    external: true
  SUPERADMIN_PRIV_KEY:
    external: true
  RABBITMQ_PUB_KEY:
    external: true
  RABBITMQ_PRIV_KEY:
    external: true
  IMS_PUB_KEY:
    external: true
  IMS_PRIV_KEY:
    external: true
  SERVER_ID:
    external: true
  compare_MONGODB_PASSWORD:
    external: true
  compare_MONGODB_ROOT_PASSWORD:
    external: true
  compare_INITDB_MONGODB_ROOT_PASSWORD:
    external: true


services:

  rabbitmq:
    env_file:
      - ".env"
    image: 'cytomine/rabbitmq:v1.1.2'
    restart: always
    networks:
      network_3:
        aliases:
          - rabbitmq
      software_router:
        aliases:
          - rabbitmq
    expose:
      - '5672'
      - '15672'


  postgresql:
    env_file:
      - ".env"
    image: 'cytomine/postgis:v2.0.0'
    restart: always
    networks:
      network_3:
        aliases:
          - postgresql
    volumes:
      - "postgis_data:/var/lib/postgresql"


  mongodb:
    env_file:
      - ".env"
    image: 'cytomine/mongodb:v1.1.2'
    restart: always
    networks:
      network_3:
        aliases:
          - mongodb
    volumes:
      - mongodb_data:/data/db
    expose:
      - '27017'


  bioformat:
    env_file:
      - ".env"
    image: 'cytomine/bioformat:v1.1.2'
    restart: always
    networks:
      network_2:
        aliases:
          - bioformat
    environment:
      - "BIOFORMAT_PORT=${BIOFORMAT_PORT}"
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"

  memcached:
    env_file:
      - ".env"
    build:
      context: "./memcached"
    image: "docker.pkg.github.com/histographer/infrastructure/memcached"
    restart: always
    networks:
      network_1:
        aliases:
          - memcached


  iipoff:
    env_file:
      - ".env"
    build:
      context: "./iipOff"
    image: "docker.pkg.github.com/histographer/infrastructure/iipoff"
    depends_on:
      - memcached
    restart: always
    privileged: true
    networks:
      network_1:
        aliases:
          - iipoff
      nginx:
        aliases:
          - iipoff
    volumes:
      - "${IMS_STORAGE_PATH}:$IMS_STORAGE_PATH"


  iipcyto:
    env_file:
      - ".env"
    build:
      context: "./iipCyto"
    image: "docker.pkg.github.com/histographer/infrastructure/iipcyto"
    restart: always
    networks:
      network_1:
        aliases:
          - iipcyto
      nginx:
        aliases:
          - iipcyto
    privileged: true
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"


  ims:
    env_file:
      - ".env"
    secrets:
      - IMS_PUB_KEY
      - IMS_PRIV_KEY
    build:
      context: "./ims"
    image: "docker.pkg.github.com/histographer/infrastructure/ims"
    restart: always
    depends_on:
      - core
    networks:
      network_1:
        aliases:
          - ims
      network_2:
        aliases:
          - ims
      nginx:
        aliases:
          - ims
    volumes:
      - "${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}"
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"

  core:
    env_file:
      - ".env"
    secrets:
      - ADMIN_PWD
      - ADMIN_PUB_KEY
      - ADMIN_PRIV_KEY
      - SUPERADMIN_PUB_KEY
      - SUPERADMIN_PRIV_KEY
      - IMS_PUB_KEY
      - IMS_PRIV_KEY
      - RABBITMQ_PRIV_KEY
      - RABBITMQ_PUB_KEY
      - SERVER_ID
    restart: always
    depends_on:
      - mongodb
      - postgresql
      - rabbitmq
    build:
      context: "./core"
    image: "docker.pkg.github.com/histographer/infrastructure/core"
    networks:
      network_3:
        aliases:
          - core
      nginx:
        aliases:
          - core


  digipat-frontend:
    env_file:
      - ".env"
    restart: always
    image: "docker.pkg.github.com/histographer/digipat-frontend/digipat-frontend"
    networks:
      nginx:
        aliases:
          - digipat-frontend
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    expose:
      - '80'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s



  compare-frontend:
    env_file:
      - ".env"
    restart: always
    image: "docker.pkg.github.com/histographer/compare-frontend/compare-frontend"
    networks:
      nginx:
        aliases:
          - compare-frontend
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    expose:
      - '80'

  # TODO: Should use the existing mongodb service later
  compare-db:
    env_file:
      - ".env"
    image: mongo:latest
    restart: always
    networks:
      compare:
        aliases:
          - compare-db
    secrets:
      - compare_INITDB_MONGODB_ROOT_PASSWORD
      - compare_MONGODB_PASSWORD
    volumes:
      - compare-data:/data/db
      - ./database/db-init/:/docker-entrypoint-initdb.d

  compare-backend:
    restart: always
    env_file:
      - ".env"
    secrets:
      - compare_MONGODB_PASSWORD
    image: "docker.pkg.github.com/histographer/compare-backend/compare-backend"
    depends_on:
      - compare-db
    networks:
      nginx:
        aliases:
          - compare-backend
      compare:
        aliases:
          - compare-backend


  analysis-rest-api:
    image: "docker.pkg.github.com/histographer/analysis-rest-api/analysis-rest-api"
    env_file:
      - ".env"
    networks:
      nginx:
        aliases:
          - analysis-rest-api
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 120s



  nginx:
    restart: always
    env_file:
      - ".env"
    depends_on:
      - digipat-frontend
      - core
      - ims
      - iipoff
      - iipcyto
      - compare-frontend
      - compare-backend
      - analysis-rest-api
    image: "docker.pkg.github.com/histographer/infrastructure/nginx-prod"
    build:
      context: "./nginx"
    networks:
      nginx:
        aliases:
          - nginx
    volumes:
      - "${IMS_BUFFER_PATH}:/tmp/uploaded"
    ports:
      - 80:80


  software_router:
    env_file:
      - ".env"
    secrets:
      - RABBITMQ_PUB_KEY
      - RABBITMQ_PRIV_KEY
    build:
      context: "./software_router"
    image: "docker.pkg.github.com/histographer/infrastructure/software_router"
    privileged: true
    depends_on:
      - core
      - nginx
    networks:
      software_router:
        aliases:
          - software_router
    volumes:
      - "${ALGO_PATH}:/software_router/algo/"





